use super::*;
use std::collections::HashMap;

/// The Lean model's exported table (`formal/resource_table.json`,
/// regenerated by `scripts/check_formal.sh --write`). Only accepted
/// transitions are listed; every other (state, event) pair is a refusal.
fn formal_table() -> HashMap<(ResourceState, ResourceEvent), ResourceState> {
    let text = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/formal/resource_table.json"
    ));
    let rows: Vec<[String; 3]> = serde_json::from_str(text).expect("resource_table.json is JSON");
    let mut map = HashMap::new();
    for [s, e, t] in rows {
        let s = ResourceState::from_label(&s).unwrap_or_else(|| panic!("unknown state {s}"));
        let e = ResourceEvent::from_label(&e).unwrap_or_else(|| panic!("unknown event {e}"));
        let t = ResourceState::from_label(&t).unwrap_or_else(|| panic!("unknown state {t}"));
        assert!(
            map.insert((s, e), t).is_none(),
            "duplicate row ({s}, {})",
            e.label()
        );
    }
    map
}

#[test]
fn rust_resource_table_equals_the_lean_model_for_every_pair() {
    let formal = formal_table();
    let mut accepted = 0;
    for (s, e, rust) in table() {
        let lean = formal.get(&(s, e)).copied();
        assert_eq!(
            rust,
            lean,
            "({s}, {}): Rust {rust:?} but the Lean model says {lean:?}",
            e.label()
        );
        if rust.is_some() {
            accepted += 1;
        }
    }
    assert_eq!(
        accepted,
        formal.len(),
        "every Lean row is a Rust transition"
    );
    assert_eq!(
        table().len(),
        ResourceState::ALL.len() * ResourceEvent::ALL.len()
    );
}

#[test]
fn labels_round_trip_and_match_serde() {
    for s in ResourceState::ALL {
        assert_eq!(ResourceState::from_label(s.label()), Some(s));
        assert_eq!(
            serde_json::to_string(&s).unwrap(),
            format!("\"{}\"", s.label())
        );
    }
    for e in ResourceEvent::ALL {
        assert_eq!(ResourceEvent::from_label(e.label()), Some(e));
        assert_eq!(
            serde_json::to_string(&e).unwrap(),
            format!("\"{}\"", e.label())
        );
    }
}

#[test]
fn r4_released_only_on_confirmation() {
    for (s, e, t) in table() {
        if t == Some(ResourceState::Released) {
            assert!(
                e == ResourceEvent::Stopped
                    || (s == ResourceState::Requested && e == ResourceEvent::Drain),
                "{s} --{}--> released without confirmation",
                e.label()
            );
        }
    }
    // Giving up is a leak, never a release.
    assert_eq!(
        ResourceMachine::next(&ResourceState::Draining, &ResourceEvent::Abandon),
        Ok(ResourceState::Leaked)
    );
    assert_eq!(
        ResourceMachine::on_enter(&ResourceState::Leaked),
        vec![Effect::LeakAlarm]
    );
}

#[test]
fn oracle_flags_an_unconfirmed_release() {
    assert!(ResourceMachine::check_step(
        &ResourceState::Draining,
        &ResourceEvent::Abandon,
        &ResourceState::Released
    )
    .is_err());
}

#[test]
fn server_port_label_from_the_first_registry_reads_as_port() {
    let kind: ResourceKind = serde_json::from_str("\"server_port\"").unwrap();
    assert_eq!(kind, ResourceKind::Port);
    assert!(!kind.is_drainable());
}
