use super::*;
use crate::lifecycle::{EventLog, Tracked};
use std::collections::HashMap;

/// The Lean model's exported table (`formal/task_table.json`, regenerated by
/// `scripts/check_formal.sh --write`). Only accepted transitions are listed;
/// every other (state, event) pair is a refusal.
fn formal_table() -> HashMap<(TaskState, TaskEvent), TaskState> {
    let text = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/formal/task_table.json"
    ));
    let rows: Vec<[String; 3]> = serde_json::from_str(text).expect("task_table.json is JSON");
    let mut map = HashMap::new();
    for [s, e, t] in rows {
        let s = TaskState::from_label(&s).unwrap_or_else(|| panic!("unknown state {s}"));
        let e = TaskEvent::from_label(&e).unwrap_or_else(|| panic!("unknown event {e}"));
        let t = TaskState::from_label(&t).unwrap_or_else(|| panic!("unknown state {t}"));
        assert!(
            map.insert((s, e), t).is_none(),
            "duplicate row ({s}, {})",
            e.label()
        );
    }
    map
}

#[test]
fn rust_table_equals_the_lean_model_for_every_pair() {
    let formal = formal_table();
    let mut accepted = 0;
    for (s, e, rust) in table() {
        let lean = formal.get(&(s, e)).copied();
        assert_eq!(
            rust,
            lean,
            "({s}, {}): Rust {:?} but the Lean model says {:?}",
            e.label(),
            rust,
            lean
        );
        // `next` is the same function as the table, including refusals.
        match (TaskMachine::next(&s, &e), lean) {
            (Ok(n), Some(t)) => assert_eq!(n, t),
            (Err(err), None) => {
                assert_eq!(err.from, s.label());
                assert_eq!(err.event, e.label());
                assert_eq!(err.entity, crate::lifecycle::Entity::Task);
            }
            (got, want) => panic!("({s}, {}): next={got:?}, lean={want:?}", e.label()),
        }
        if rust.is_some() {
            accepted += 1;
        }
    }
    assert_eq!(accepted, formal.len(), "no Lean row is left unmatched");
    assert_eq!(table().len(), TaskState::ALL.len() * TaskEvent::ALL.len());
}

#[test]
fn labels_round_trip_and_match_the_lean_names() {
    for s in TaskState::ALL {
        assert_eq!(TaskState::from_label(s.label()), Some(s));
    }
    for e in TaskEvent::ALL {
        assert_eq!(TaskEvent::from_label(e.label()), Some(e));
    }
    // Serde uses the same names as the log/table.
    assert_eq!(
        serde_json::to_string(&TaskEvent::NeedInput).unwrap(),
        "\"need_input\""
    );
    assert_eq!(
        serde_json::to_string(&TaskState::Interrupted).unwrap(),
        "\"interrupted\""
    );
}

#[test]
fn p1_terminal_states_are_sticky_except_interrupted_resume() {
    for s in TaskState::ALL.into_iter().filter(|s| s.is_terminal()) {
        for e in TaskEvent::ALL {
            let next = TaskMachine::next(&s, &e);
            if s == TaskState::Interrupted && e == TaskEvent::Resume {
                assert_eq!(next, Ok(TaskState::Queued));
            } else {
                assert!(next.is_err(), "terminal {s} accepted {}", e.label());
            }
        }
    }
}

#[test]
fn p2_every_live_state_has_a_timeout_exit_to_failed() {
    for s in TaskState::ALL.into_iter().filter(|s| !s.is_terminal()) {
        assert_eq!(
            TaskMachine::next(&s, &TaskEvent::Timeout),
            Ok(TaskState::Failed),
            "{s}"
        );
    }
}

#[test]
fn terminal_states_request_teardown() {
    for s in TaskState::ALL {
        let effects = TaskMachine::on_enter(&s);
        if s.is_terminal() {
            assert_eq!(effects, vec![Effect::TeardownOwned], "{s}");
        } else {
            assert!(effects.is_empty(), "{s}");
        }
    }
}

#[test]
fn oracle_accepts_every_table_transition() {
    for (s, e, t) in table() {
        if let Some(t) = t {
            assert_eq!(
                TaskMachine::check_step(&s, &e, &t),
                Ok(()),
                "{s} {}",
                e.label()
            );
        }
    }
}

#[test]
fn oracle_flags_a_terminal_state_being_left() {
    let err = TaskMachine::check_step(
        &TaskState::Completed,
        &TaskEvent::Start,
        &TaskState::Planning,
    )
    .expect_err("leaving completed violates P1");
    assert!(err.contains("P1"), "{err}");
    // Resuming an interrupted task is the one allowed exit.
    assert_eq!(
        TaskMachine::check_step(
            &TaskState::Interrupted,
            &TaskEvent::Resume,
            &TaskState::Queued
        ),
        Ok(())
    );
    // Any other exit from interrupted is flagged.
    assert!(TaskMachine::check_step(
        &TaskState::Interrupted,
        &TaskEvent::Start,
        &TaskState::Planning
    )
    .is_err());
}

#[test]
fn refused_event_is_a_typed_error_and_changes_nothing() {
    let dir = tempfile::tempdir().unwrap();
    let log = EventLog::at(dir.path().join("events.jsonl"));
    let mut t: Tracked<TaskMachine> = Tracked::new("t-1", TaskState::Completed, log.clone());
    let err = t.apply(TaskEvent::Start, "retry").unwrap_err();
    assert_eq!(
        err.to_string(),
        "invalid task transition: event `start` is refused in state `completed`"
    );
    assert_eq!(*t.state(), TaskState::Completed);
    assert!(log.read_all().0.is_empty(), "a refusal records nothing");
}

/// A deliberately wrong machine: `completed --start--> queued`. The table
/// accepts it, the oracle must not.
#[derive(Debug, Clone, Copy)]
struct BrokenTaskMachine;

impl Machine for BrokenTaskMachine {
    type State = TaskState;
    type Event = TaskEvent;
    const ENTITY: crate::lifecycle::Entity = crate::lifecycle::Entity::Task;

    fn next(state: &TaskState, event: &TaskEvent) -> Result<TaskState, InvalidTransition> {
        if *state == TaskState::Completed && *event == TaskEvent::Start {
            return Ok(TaskState::Queued);
        }
        TaskMachine::next(state, event)
    }
    fn on_enter(state: &TaskState) -> Vec<Effect> {
        TaskMachine::on_enter(state)
    }
    fn is_terminal(state: &TaskState) -> bool {
        state.is_terminal()
    }
    fn check_step(from: &TaskState, event: &TaskEvent, to: &TaskState) -> Result<(), String> {
        TaskMachine::check_step(from, event, to)
    }
}

#[cfg(debug_assertions)]
#[test]
#[should_panic(expected = "lifecycle oracle: P1 violated")]
fn runtime_oracle_trips_in_debug_builds() {
    let mut t: Tracked<BrokenTaskMachine> =
        Tracked::new("t-broken", TaskState::Completed, EventLog::disabled());
    let _ = t.apply(TaskEvent::Start, "should never be accepted");
}
