//! Configuration provenance tracking.
//!
//! Each effective config value records where it came from — the default
//! value, a TOML file, an environment variable, a profile section, a CLI
//! argument, or auto-configuration.  The `ConfigSources` map stores the
//! provenance for individual top-level fields so `selfware config show`
//! can annotate each effective value.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

/// Where a particular config value originated.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConfigSource {
    /// Hard-coded default in the source.
    Default,
    /// Loaded from a TOML configuration file.
    ConfigFile(PathBuf),
    /// Set by an environment variable (name held inside, e.g. `SELFWARE_MODEL`).
    EnvVar(String),
    /// Inherited from a named model profile (e.g. `qwen3.6-*`).
    Profile(String),
    /// Set by a CLI argument (flag name held inside, e.g. `--model`).
    CliArg(String),
    /// Generated by auto-calibration / unpack.
    AutoConfig,
}

impl ConfigSource {
    /// Short human label suitable for `selfware config show`.
    pub fn label(&self) -> String {
        match self {
            ConfigSource::Default => "default".to_string(),
            ConfigSource::ConfigFile(path) => path.display().to_string(),
            ConfigSource::EnvVar(name) => format!("{} env", name),
            ConfigSource::Profile(name) => format!("profile: {}", name),
            ConfigSource::CliArg(flag) => format!("cli: {}", flag),
            ConfigSource::AutoConfig => "auto-config".to_string(),
        }
    }
}

/// Map of dotted field name → source. Stored alongside the live `Config`
/// so callers can ask `config.source_of("endpoint")`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConfigSources {
    inner: HashMap<String, ConfigSource>,
}

impl ConfigSources {
    pub fn new() -> Self {
        Self::default()
    }

    /// Record (or replace) the source for a dotted field name.
    pub fn set(&mut self, key: impl Into<String>, source: ConfigSource) {
        self.inner.insert(key.into(), source);
    }

    /// Look up the recorded source for a dotted field name.
    pub fn get(&self, key: &str) -> Option<&ConfigSource> {
        self.inner.get(key)
    }

    /// Iterator over (key, source) pairs in insertion-stable sorted order.
    pub fn iter(&self) -> impl Iterator<Item = (&String, &ConfigSource)> {
        let mut keys: Vec<&String> = self.inner.keys().collect();
        keys.sort();
        keys.into_iter().map(move |k| (k, &self.inner[k]))
    }

    pub fn len(&self) -> usize {
        self.inner.len()
    }

    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }
}

/// How a config path is shown to the user: relative (`selfware.toml`,
/// `conf/x.toml`) when it lies under `cwd`, `~/…` when under `home`, else
/// as given. Pure so it is testable; see [`display_config_path`].
pub fn display_path_for(
    path: &std::path::Path,
    cwd: Option<&std::path::Path>,
    home: Option<&std::path::Path>,
) -> String {
    if path.is_relative() {
        return path.display().to_string();
    }
    if let Some(rel) = cwd.and_then(|c| path.strip_prefix(c).ok()) {
        if !rel.as_os_str().is_empty() {
            return rel.display().to_string();
        }
    }
    if let Some(rel) = home.and_then(|h| path.strip_prefix(h).ok()) {
        return format!("~/{}", rel.display());
    }
    path.display().to_string()
}

/// [`display_path_for`] against the process's cwd and home directory — the
/// one formatter for config paths on the user-facing surfaces (the startup
/// `config:` line, doctor, bug reports), so a long absolute path is not
/// repeated on every command (0.9.1 field finding).
pub fn display_config_path(path: &std::path::Path) -> String {
    let cwd = std::env::current_dir().ok();
    let home = dirs::home_dir();
    display_path_for(path, cwd.as_deref(), home.as_deref())
}

static CONFIG_LINE_SUPPRESSED: std::sync::atomic::AtomicBool =
    std::sync::atomic::AtomicBool::new(false);

/// Suppress the loader's startup `config: <path>` line for this process.
/// Set by subcommands that report the config file themselves (`doctor`,
/// `llm-doctor`), which otherwise printed the path twice.
pub fn set_config_line_suppressed(suppressed: bool) {
    CONFIG_LINE_SUPPRESSED.store(suppressed, std::sync::atomic::Ordering::Relaxed);
}

/// Whether [`set_config_line_suppressed`] is in effect.
pub fn config_line_suppressed() -> bool {
    CONFIG_LINE_SUPPRESSED.load(std::sync::atomic::Ordering::Relaxed)
}

#[cfg(test)]
#[path = "../../tests/unit/config/provenance/provenance_test.rs"]
mod tests;
