//! Configuration provenance tracking.
//!
//! Each effective config value records where it came from — the default
//! value, a TOML file, an environment variable, a profile section, a CLI
//! argument, or auto-configuration.  The `ConfigSources` map stores the
//! provenance for individual top-level fields so `selfware config show`
//! can annotate each effective value.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

/// Where a particular config value originated.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConfigSource {
    /// Hard-coded default in the source.
    Default,
    /// Loaded from a TOML configuration file.
    ConfigFile(PathBuf),
    /// Set by an environment variable (name held inside, e.g. `SELFWARE_MODEL`).
    EnvVar(String),
    /// Inherited from a named model profile (e.g. `qwen3.6-*`).
    Profile(String),
    /// Set by a CLI argument (flag name held inside, e.g. `--model`).
    CliArg(String),
    /// Generated by auto-calibration / unpack.
    AutoConfig,
}

impl ConfigSource {
    /// Short human label suitable for `selfware config show`.
    pub fn label(&self) -> String {
        match self {
            ConfigSource::Default => "default".to_string(),
            ConfigSource::ConfigFile(path) => path.display().to_string(),
            ConfigSource::EnvVar(name) => format!("{} env", name),
            ConfigSource::Profile(name) => format!("profile: {}", name),
            ConfigSource::CliArg(flag) => format!("cli: {}", flag),
            ConfigSource::AutoConfig => "auto-config".to_string(),
        }
    }
}

/// Map of dotted field name → source. Stored alongside the live `Config`
/// so callers can ask `config.source_of("endpoint")`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ConfigSources {
    inner: HashMap<String, ConfigSource>,
}

impl ConfigSources {
    pub fn new() -> Self {
        Self::default()
    }

    /// Record (or replace) the source for a dotted field name.
    pub fn set(&mut self, key: impl Into<String>, source: ConfigSource) {
        self.inner.insert(key.into(), source);
    }

    /// Look up the recorded source for a dotted field name.
    pub fn get(&self, key: &str) -> Option<&ConfigSource> {
        self.inner.get(key)
    }

    /// Iterator over (key, source) pairs in insertion-stable sorted order.
    pub fn iter(&self) -> impl Iterator<Item = (&String, &ConfigSource)> {
        let mut keys: Vec<&String> = self.inner.keys().collect();
        keys.sort();
        keys.into_iter().map(move |k| (k, &self.inner[k]))
    }

    pub fn len(&self) -> usize {
        self.inner.len()
    }

    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn label_for_default() {
        assert_eq!(ConfigSource::Default.label(), "default");
    }

    #[test]
    fn label_for_config_file() {
        let s = ConfigSource::ConfigFile(PathBuf::from("/tmp/foo/selfware.toml"));
        assert_eq!(s.label(), "/tmp/foo/selfware.toml");
    }

    #[test]
    fn label_for_env_var() {
        let s = ConfigSource::EnvVar("SELFWARE_ENDPOINT".to_string());
        assert_eq!(s.label(), "SELFWARE_ENDPOINT env");
    }

    #[test]
    fn label_for_profile() {
        let s = ConfigSource::Profile("qwen3.6-*".to_string());
        assert_eq!(s.label(), "profile: qwen3.6-*");
    }

    #[test]
    fn label_for_cli_arg() {
        let s = ConfigSource::CliArg("--model".to_string());
        assert_eq!(s.label(), "cli: --model");
    }

    #[test]
    fn sources_set_and_get() {
        let mut s = ConfigSources::new();
        s.set("endpoint", ConfigSource::Default);
        s.set(
            "model",
            ConfigSource::ConfigFile(PathBuf::from("/tmp/x.toml")),
        );
        assert_eq!(s.get("endpoint"), Some(&ConfigSource::Default));
        assert!(matches!(s.get("model"), Some(ConfigSource::ConfigFile(_))));
        assert_eq!(s.get("missing"), None);
        assert_eq!(s.len(), 2);
    }

    #[test]
    fn sources_iter_is_sorted() {
        let mut s = ConfigSources::new();
        s.set("model", ConfigSource::Default);
        s.set("endpoint", ConfigSource::Default);
        s.set("temperature", ConfigSource::Default);
        let keys: Vec<&String> = s.iter().map(|(k, _)| k).collect();
        assert_eq!(keys, vec!["endpoint", "model", "temperature"]);
    }
}
