//! Run supervisor — process model that owns N concurrent agent runs.
//!
//! This is **Increment 1** of the `RunSupervisor`. It provides the core
//! concurrent-run lifecycle (`spawn`, `abort`, `status`, `list`) plus an
//! agent-launching convenience (`start`) and documented stubs for `attach`,
//! `pause`, and `resume` which land in later increments.
//!
//! The design deliberately keeps the testable primitive — [`RunSupervisor::spawn`]
//! — independent of any live LLM. Tests spawn trivial futures (`async { Ok(()) }`,
//! `async { Err(...) }`, long sleeps) and assert state transitions without
//! touching [`crate::agent::Agent`], which requires a configured API client.
//!
//! Cancellation uses [`std::sync::atomic::AtomicBool`] (no `tokio_util`
//! dependency). An `abort()` flips the flag **and** calls `JoinHandle::abort`,
//! so cooperatively-polling futures can observe the flag while also receiving an
//! immediate hard-cancel.

use std::collections::HashMap;
use std::future::Future;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::Arc;

use tokio::sync::RwLock;
use tokio::task::JoinHandle;

use crate::agent::tui_events::{AgentEvent, BroadcastEmitter, EventEmitter};

/// Lifecycle status of a single run.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunStatus {
    /// The run is currently executing.
    Running,
    /// The run is paused (not yet implemented — see [`RunSupervisor::pause`]).
    Paused,
    /// The run completed successfully (`Ok(())`).
    Completed,
    /// The run failed (`Err(_)`).
    Failed,
    /// The run was aborted via [`RunSupervisor::abort`].
    Aborted,
}

/// Opaque, monotonic identifier for a run.
///
/// Generated by an [`AtomicU64`] counter on the supervisor — no dates or
/// randomness involved, so IDs are strictly monotonic within a supervisor
/// instance and trivially comparable/orderable.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct RunId(pub u64);

impl std::fmt::Display for RunId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "run-{}", self.0)
    }
}

/// Capacity of each run's broadcast event channel.
const EVENT_CHANNEL_CAPACITY: usize = 256;

/// Internal handle for a single run.
struct RunHandle {
    status: Arc<RwLock<RunStatus>>,
    cancel: Arc<AtomicBool>,
    join: JoinHandle<()>,
    /// Human-readable task description for diagnostics/listing.
    #[allow(dead_code)]
    task: String,
    /// Per-run broadcast sender for `AgentEvent`s.
    ///
    /// Every run — whether created via [`RunSupervisor::spawn`] (pure future)
    /// or [`RunSupervisor::start`] (real agent) — gets its own broadcast
    /// channel so that [`attach`](RunSupervisor::attach) always works.
    /// For `spawn`-only runs nothing may ever emit, but the channel exists
    /// so `attach` can return a live subscriber regardless.
    events: tokio::sync::broadcast::Sender<AgentEvent>,
}

/// Supervisor owning N concurrent agent runs.
///
/// Create with [`RunSupervisor::new`], then drive runs via [`spawn`](Self::spawn)
/// (generic, testable) or [`start`](Self::start) (builds a real
/// [`crate::agent::Agent`] run — requires a live LLM).
pub struct RunSupervisor {
    runs: RwLock<HashMap<RunId, RunHandle>>,
    next_id: AtomicU64,
}

impl Default for RunSupervisor {
    fn default() -> Self {
        Self::new()
    }
}

impl RunSupervisor {
    /// Create an empty supervisor with no runs.
    pub fn new() -> Self {
        Self {
            runs: RwLock::new(HashMap::new()),
            next_id: AtomicU64::new(1),
        }
    }

    /// Spawn a generic future as a supervised run and return its [`RunId`].
    ///
    /// This is the **core testable primitive**: tests pass trivial futures
    /// (`async { Ok(()) }`, `async { Err(...) }`, a long `sleep`) and assert
    /// state transitions without needing a live LLM.
    ///
    /// The future runs on a dedicated tokio task. On completion the run's
    /// status becomes [`RunStatus::Completed`] (for `Ok`) or
    /// [`RunStatus::Failed`] (for `Err`) — **unless** the cancel flag was set
    /// first, in which case the status becomes [`RunStatus::Aborted`]
    /// regardless of the future's own outcome.
    ///
    /// The `RunId` is allocated with a monotonic `fetch_add` on an internal
    /// [`AtomicU64`]; no dates/randomness are used.
    pub async fn spawn<F>(&self, task: String, run: F) -> RunId
    where
        F: Future<Output = anyhow::Result<()>> + Send + 'static,
    {
        let id = RunId(self.next_id.fetch_add(1, Ordering::Relaxed));
        let status = Arc::new(RwLock::new(RunStatus::Running));
        let cancel = Arc::new(AtomicBool::new(false));
        let (event_tx, _event_rx) =
            tokio::sync::broadcast::channel::<AgentEvent>(EVENT_CHANNEL_CAPACITY);

        let status_clone = Arc::clone(&status);
        let cancel_clone = Arc::clone(&cancel);

        let join = tokio::spawn(async move {
            let result = run.await;
            // If the cancel flag was flipped (abort), treat the outcome as
            // Aborted regardless of what the future returned.
            let final_status = if cancel_clone.load(Ordering::Relaxed) {
                RunStatus::Aborted
            } else {
                match result {
                    Ok(()) => RunStatus::Completed,
                    Err(_) => RunStatus::Failed,
                }
            };
            *status_clone.write().await = final_status;
        });

        let handle = RunHandle {
            status,
            cancel,
            join,
            task,
            events: event_tx,
        };

        self.runs.write().await.insert(id, handle);
        id
    }

    /// Like [`spawn`](Self::spawn) but uses a caller-provided broadcast sender
    /// for the run's event channel instead of creating a new one.
    ///
    /// This lets [`start`](Self::start) pre-create the channel, wire a
    /// [`BroadcastEmitter`] onto the agent, and then pass the *same* sender
    /// here so that [`attach`](Self::attach) subscribers receive events the
    /// agent emits.
    async fn spawn_with_events<F>(
        &self,
        task: String,
        event_tx: tokio::sync::broadcast::Sender<AgentEvent>,
        run: F,
    ) -> RunId
    where
        F: Future<Output = anyhow::Result<()>> + Send + 'static,
    {
        let id = RunId(self.next_id.fetch_add(1, Ordering::Relaxed));
        let status = Arc::new(RwLock::new(RunStatus::Running));
        let cancel = Arc::new(AtomicBool::new(false));

        let status_clone = Arc::clone(&status);
        let cancel_clone = Arc::clone(&cancel);

        let join = tokio::spawn(async move {
            let result = run.await;
            let final_status = if cancel_clone.load(Ordering::Relaxed) {
                RunStatus::Aborted
            } else {
                match result {
                    Ok(()) => RunStatus::Completed,
                    Err(_) => RunStatus::Failed,
                }
            };
            *status_clone.write().await = final_status;
        });

        let handle = RunHandle {
            status,
            cancel,
            join,
            task,
            events: event_tx,
        };

        self.runs.write().await.insert(id, handle);
        id
    }

    /// Build a real agent run from a [`crate::config::Config`] and spawn it.
    ///
    /// This constructs an [`crate::agent::Agent`] and calls
    /// [`Agent::run_task`](crate::agent::Agent::run_task). **Requires a live
    /// LLM** (a configured API client); tests should use [`spawn`](Self::spawn)
    /// instead.
    ///
    /// A per-run `tokio::sync::broadcast` channel is created and a
    /// [`BroadcastEmitter`] is wired onto the agent via
    /// [`Agent::with_event_emitter`](crate::agent::Agent::with_event_emitter)
    /// before `run_task` is called, so that [`attach`](Self::attach) returns a
    /// live subscriber that receives the agent's `AgentEvent`s.
    pub async fn start(&self, task: String, config: crate::config::Config) -> RunId {
        let task_for_run = task.clone();
        // We create the broadcast channel here and clone the sender into the
        // RunHandle (via spawn) while also wrapping a clone in a
        // BroadcastEmitter for the agent.
        let (event_tx, _event_rx) =
            tokio::sync::broadcast::channel::<AgentEvent>(EVENT_CHANNEL_CAPACITY);
        let emitter: Arc<dyn EventEmitter> = Arc::new(BroadcastEmitter::new(event_tx.clone()));

        let task_for_spawn = task.clone();
        // Call spawn but override its internal channel with our pre-built one
        // by using a lower-level path: we can't easily inject into spawn, so
        // instead we use spawn_with_events.
        let id = self
            .spawn_with_events(task_for_spawn, event_tx, async move {
                let mut agent = crate::agent::Agent::new(config).await?;
                agent = agent.with_event_emitter(emitter);
                agent.run_task(&task_for_run).await
            })
            .await;
        id
    }

    /// Abort a run: set the cancel flag, abort the `JoinHandle`, and mark the
    /// status [`RunStatus::Aborted`].
    ///
    /// Returns `true` if the run existed, `false` otherwise. Aborting an
    /// already-completed run is harmless (it just re-sets an already-finished
    /// status).
    pub async fn abort(&self, id: &RunId) -> bool {
        let runs = self.runs.write().await;
        let Some(handle) = runs.get(id) else {
            return false;
        };
        handle.cancel.store(true, Ordering::Relaxed);
        handle.join.abort();
        *handle.status.write().await = RunStatus::Aborted;
        true
    }

    /// Read the current [`RunStatus`] of a run, or `None` if it doesn't exist.
    pub async fn status(&self, id: &RunId) -> Option<RunStatus> {
        let runs = self.runs.read().await;
        match runs.get(id) {
            Some(h) => {
                let st = *h.status.read().await;
                Some(st)
            }
            None => None,
        }
    }

    /// Snapshot of all runs and their current statuses.
    pub async fn list(&self) -> Vec<(RunId, RunStatus)> {
        let runs = self.runs.read().await;
        let mut out = Vec::with_capacity(runs.len());
        for (id, handle) in runs.iter() {
            let st = *handle.status.read().await;
            out.push((*id, st));
        }
        out
    }

    /// Attach to a run's event stream.
    ///
    /// Returns a live `tokio::sync::broadcast::Receiver<AgentEvent>` for the
    /// run's event channel, or `None` if the run id is unknown.
    ///
    /// Multiple callers can attach to the same run simultaneously — the
    /// underlying `tokio::sync::broadcast` channel fans out each emitted
    /// `AgentEvent` to every active subscriber.
    ///
    /// For runs created via [`start`](Self::start), the agent's events flow
    /// through this channel in real time. For runs created via
    /// [`spawn`](Self::spawn) (pure futures), the channel exists but may
    /// never receive events unless something writes to it directly.
    pub async fn attach(&self, id: &RunId) -> Option<tokio::sync::broadcast::Receiver<AgentEvent>> {
        let runs = self.runs.read().await;
        runs.get(id).map(|h| h.events.subscribe())
    }

    /// Pause a running run.
    ///
    /// **Not yet implemented (Increment 2).** Currently returns an error.
    pub async fn pause(&self, _id: &RunId) -> anyhow::Result<()> {
        anyhow::bail!("pause not yet implemented (inc2)")
    }

    /// Resume a paused run.
    ///
    /// **Not yet implemented (Increment 2).** Currently returns an error.
    pub async fn resume(&self, _id: &RunId) -> anyhow::Result<()> {
        anyhow::bail!("resume not yet implemented (inc2)")
    }

    /// Emit an `AgentEvent` directly to a run's broadcast channel.
    ///
    /// This is primarily intended for testing fan-out without a live LLM:
    /// a test can [`spawn`](Self::spawn) a trivial future, [`attach`](Self::attach)
    /// multiple subscribers, then call this to push an event and verify every
    /// subscriber receives it.
    ///
    /// Returns `true` if the run existed, `false` otherwise.
    #[allow(dead_code)]
    pub(crate) async fn emit_event(&self, id: &RunId, event: AgentEvent) -> bool {
        let runs = self.runs.read().await;
        match runs.get(id) {
            Some(h) => {
                let _ = h.events.send(event);
                true
            }
            None => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    /// Wait (with a timeout) for a run to reach the expected status.
    ///
    /// Polls `status()` with short yields so the spawned task has a chance to
    /// finish. Avoids fixed long sleeps.
    async fn wait_for_status(
        sup: &RunSupervisor,
        id: &RunId,
        expected: RunStatus,
        timeout: Duration,
    ) -> bool {
        let deadline = tokio::time::Instant::now() + timeout;
        loop {
            if let Some(s) = sup.status(id).await {
                if s == expected {
                    return true;
                }
            } else {
                return false;
            }
            if tokio::time::Instant::now() >= deadline {
                return false;
            }
            // Yield to let the spawned task make progress.
            tokio::task::yield_now().await;
            tokio::time::sleep(Duration::from_millis(2)).await;
        }
    }

    #[tokio::test]
    async fn spawn_ok_completes() {
        let sup = RunSupervisor::new();
        let id = sup.spawn("trivial-ok".into(), async { Ok(()) }).await;

        assert!(
            wait_for_status(&sup, &id, RunStatus::Completed, Duration::from_secs(2)).await,
            "run should reach Completed"
        );

        // list() must include it.
        let listed = sup.list().await;
        assert!(listed
            .iter()
            .any(|(rid, st)| rid == &id && *st == RunStatus::Completed));
    }

    #[tokio::test]
    async fn spawn_err_fails() {
        let sup = RunSupervisor::new();
        let id = sup
            .spawn("trivial-err".into(), async { Err(anyhow::anyhow!("boom")) })
            .await;

        assert!(
            wait_for_status(&sup, &id, RunStatus::Failed, Duration::from_secs(2)).await,
            "run should reach Failed"
        );
    }

    #[tokio::test]
    async fn spawn_running_then_abort() {
        let sup = RunSupervisor::new();
        // A genuinely long future — we abort before it completes, so no real
        // 30s wait occurs in the test.
        let id = sup
            .spawn("long-sleep".into(), async {
                tokio::time::sleep(Duration::from_secs(30)).await;
                Ok(())
            })
            .await;

        // Immediately it should be Running.
        assert_eq!(sup.status(&id).await, Some(RunStatus::Running));

        // Abort it.
        let aborted = sup.abort(&id).await;
        assert!(aborted, "abort should return true for existing id");
        assert_eq!(sup.status(&id).await, Some(RunStatus::Aborted));
    }

    #[tokio::test]
    async fn run_id_monotonic_unique() {
        let sup = RunSupervisor::new();
        let a = sup.spawn("a".into(), async { Ok(()) }).await;
        let b = sup.spawn("b".into(), async { Ok(()) }).await;
        let c = sup.spawn("c".into(), async { Ok(()) }).await;

        assert_ne!(a, b);
        assert_ne!(b, c);
        assert_ne!(a, c);
        // Monotonic: a < b < c.
        assert!(a < b);
        assert!(b < c);
    }

    #[tokio::test]
    async fn abort_nonexistent_returns_false() {
        let sup = RunSupervisor::new();
        let bogus = RunId(999_999);
        assert!(!sup.abort(&bogus).await);
    }

    #[tokio::test]
    async fn list_snapshot_reflects_state() {
        let sup = RunSupervisor::new();
        let ok = sup.spawn("ok".into(), async { Ok(()) }).await;
        let err = sup
            .spawn("err".into(), async { Err(anyhow::anyhow!("x")) })
            .await;
        let long = sup
            .spawn("long".into(), async {
                tokio::time::sleep(Duration::from_secs(30)).await;
                Ok(())
            })
            .await;

        // Wait for ok + err to settle.
        assert!(wait_for_status(&sup, &ok, RunStatus::Completed, Duration::from_secs(2)).await);
        assert!(wait_for_status(&sup, &err, RunStatus::Failed, Duration::from_secs(2)).await);

        // Abort the long one.
        assert!(sup.abort(&long).await);

        let listed = sup.list().await;
        assert_eq!(listed.len(), 3);

        let by_id: HashMap<RunId, RunStatus> = listed.into_iter().collect();
        assert_eq!(by_id[&ok], RunStatus::Completed);
        assert_eq!(by_id[&err], RunStatus::Failed);
        assert_eq!(by_id[&long], RunStatus::Aborted);
    }

    // ── Increment 2: broadcast event channel ───────────────────────────

    #[tokio::test]
    async fn attach_nonexistent_returns_none() {
        let sup = RunSupervisor::new();
        let bogus = RunId(999_999);
        assert!(sup.attach(&bogus).await.is_none());
    }

    #[tokio::test]
    async fn attach_returns_live_subscriber() {
        let sup = RunSupervisor::new();
        let id = sup.spawn("trivial".into(), async { Ok(()) }).await;

        let sub = sup.attach(&id).await;
        assert!(
            sub.is_some(),
            "attach should return Some for an existing run"
        );

        // The subscriber should be a broadcast::Receiver.
        let mut rx = sub.unwrap();

        // Emit an event and verify we receive it.
        let event = AgentEvent::Status {
            message: "hello".into(),
        };
        assert!(sup.emit_event(&id, event.clone()).await);

        let received = tokio::time::timeout(Duration::from_secs(2), rx.recv())
            .await
            .expect("recv should not time out")
            .expect("recv should succeed");

        assert_eq!(
            received,
            AgentEvent::Status {
                message: "hello".into()
            }
        );
    }

    #[tokio::test]
    async fn attach_fans_out_to_multiple_subscribers() {
        let sup = RunSupervisor::new();
        let id = sup
            .spawn("fan-out-test".into(), async {
                // Keep the run alive long enough for the test to emit + recv.
                tokio::time::sleep(Duration::from_secs(5)).await;
                Ok(())
            })
            .await;

        // Two independent subscribers on the same run.
        let mut rx1 = sup.attach(&id).await.expect("attach rx1");
        let mut rx2 = sup.attach(&id).await.expect("attach rx2");

        // Emit a single event — BOTH subscribers must receive it.
        let event = AgentEvent::Started;
        assert!(sup.emit_event(&id, event.clone()).await);

        let r1 = tokio::time::timeout(Duration::from_secs(2), rx1.recv())
            .await
            .expect("rx1 should not time out")
            .expect("rx1 recv should succeed");
        let r2 = tokio::time::timeout(Duration::from_secs(2), rx2.recv())
            .await
            .expect("rx2 should not time out")
            .expect("rx2 recv should succeed");

        assert_eq!(r1, AgentEvent::Started);
        assert_eq!(r2, AgentEvent::Started);

        // Clean up.
        sup.abort(&id).await;
    }

    #[tokio::test]
    async fn emit_event_nonexistent_returns_false() {
        let sup = RunSupervisor::new();
        let bogus = RunId(42);
        assert!(
            !sup.emit_event(&bogus, AgentEvent::Started).await,
            "emit_event on unknown run should return false"
        );
    }
}
