//! Conformance of `agent::review_coverage` with formal/ReviewBounds.lean:
//! the coverage-gate decision table (RV3), the ledger's set semantics and
//! honest completeness (RV1, RV2) as property tests against the real
//! `ReviewSession`, and the PARTIAL fold into the verdict.

use super::*;
use crate::analysis::repo_inventory::{PlanReason, ReviewPlan, ReviewScope, Totals};
use proptest::prelude::*;

fn session_with(files: &[(&str, usize)], unreadable: &[&str]) -> ReviewSession {
    let plan = ReviewPlan {
        scope: ReviewScope::whole_repository(),
        relevant: Totals::default(),
        plan: files
            .iter()
            .map(|(p, l)| PlanEntry {
                path: p.to_string(),
                lines: *l,
                in_degree: 0,
                reason: PlanReason::Remaining,
            })
            .collect(),
        unreadable: unreadable.iter().map(|u| u.to_string()).collect(),
    };
    let inventory = RepoInventory {
        root: "/repo".to_string(),
        gitignore: crate::analysis::repo_inventory::GitignoreStatus::Applied,
        totals: Totals::default(),
        binary_files: 0,
        unreadable: Vec::new(),
        code: Totals::default(),
        languages: Vec::new(),
        largest_code_files: Vec::new(),
        centrality_metric: crate::analysis::repo_inventory::CENTRALITY_METRIC,
        import_edges: 0,
        most_central: Vec::new(),
        entry_points: Vec::new(),
        files: Vec::new(),
    };
    ReviewSession::new(&inventory, plan)
}

// ------------------------------------------------------ RV3: gate table

/// The Lean model's gate table (`formal/review_gate_table.json`,
/// regenerated by `scripts/check_formal.sh --write`): inputs
/// `[complete, stopped, limit, last, no_progress, cites, nudged]`, outputs
/// `[decision, stopped', no_progress', nudged', last']`.
fn gate_table() -> Vec<[String; 12]> {
    let text = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/formal/review_gate_table.json"
    ));
    serde_json::from_str(text).expect("review_gate_table.json is JSON")
}

fn flag(s: &str) -> bool {
    match s {
        "true" => true,
        "false" => false,
        other => panic!("not a bool: {other}"),
    }
}

/// What `ReviewSession::gate` decided, in the model's words.
fn decision_name(result: &Option<String>) -> &'static str {
    match result {
        None => "accept",
        Some(text) if text.contains("review coverage incomplete") => "refuse_coverage",
        Some(text) if text.contains("review answer cites no path:line") => "refuse_citation",
        Some(text) => panic!("unknown gate refusal: {text}"),
    }
}

#[test]
fn gate_decides_every_case_as_the_lean_model() {
    let rows = gate_table();
    // 2 complete × 2 stopped × 2 limit × 3 last × 3 counters × 2 cites × 2 nudged.
    assert_eq!(rows.len(), 288, "the model enumerates every case");
    for row in &rows {
        let [complete, stopped, limit, last, np, cites, nudged, decision, stopped2, np2, nudged2, last2] =
            row;
        let mut s = session_with(&[("a.rs", 10)], &[]);
        let covered = if flag(complete) { 10 } else { 5 };
        s.record("a.rs", (1, covered));
        assert_eq!(s.complete(), flag(complete));
        let before = match last.as_str() {
            "none" => None,
            "progress" => Some(covered - 1),
            "no_progress" => Some(covered),
            other => panic!("unknown last {other}"),
        };
        s.stopped = flag(stopped).then(|| "stopped earlier".to_string());
        s.no_progress_refusals = np.parse().unwrap();
        s.covered_at_last_refusal = before;
        s.citation_nudged = flag(nudged);
        let answer = if flag(cites) {
            "The review: a.rs:3 — the loop bound is off by one."
        } else {
            "The review found nothing notable in this code."
        };
        let limit = flag(limit).then(|| "iteration budget (7 of 10 used)".to_string());
        let result = s.gate(1, answer, limit);
        let case = row[..7].join(",");
        assert_eq!(decision_name(&result), decision, "decision for [{case}]");
        assert_eq!(s.stopped.is_some(), flag(stopped2), "stopped' for [{case}]");
        assert_eq!(
            s.no_progress_refusals.to_string(),
            *np2,
            "no_progress' for [{case}]"
        );
        assert_eq!(s.citation_nudged, flag(nudged2), "nudged' for [{case}]");
        let want_last = match last2.as_str() {
            "unchanged" => before,
            "covered" => Some(covered),
            other => panic!("unknown last' {other}"),
        };
        assert_eq!(s.covered_at_last_refusal, want_last, "last' for [{case}]");
    }
}

/// RV3 on the real session: a model that never reads refuses at most a few
/// times; one that reads a line per answer is refused at most `2·L + 2`
/// times and then accepted (the Lean bound, `gate_terminates`).
#[test]
fn gate_refusals_stay_within_the_proved_bound() {
    for lines in 1..=12usize {
        for stride in 0..=3usize {
            let mut s = session_with(&[("a.rs", lines)], &[]);
            let mut refusals = 0;
            let mut read = 0;
            let mut accepted = false;
            for step in 1..=200 {
                match s.gate(step, &format!("draft {step}: a.rs:1 — x"), None) {
                    Some(t) if t.contains("review coverage incomplete") => refusals += 1,
                    Some(_) => {}
                    None => {
                        accepted = true;
                        break;
                    }
                }
                if stride > 0 && read < lines {
                    s.record("a.rs", (read + 1, (read + stride).min(lines)));
                    read = (read + stride).min(lines);
                }
            }
            assert!(accepted, "lines={lines} stride={stride}: never accepted");
            assert!(
                refusals <= 2 * lines + 2,
                "lines={lines} stride={stride}: {refusals} refusals"
            );
        }
    }
}

// --------------------------------------------- RV1 / RV2: property tests

/// One step of a generated review: record a delivered range, or judge an
/// answer (no new coverage).
#[derive(Debug, Clone)]
enum Op {
    Record { file: usize, a: usize, b: usize },
    Judge { limit: bool },
}

fn op() -> impl Strategy<Value = Op> {
    prop_oneof![
        3 => (0usize..5, 0usize..60, 0usize..60).prop_map(|(file, a, b)| Op::Record { file, a, b }),
        1 => any::<bool>().prop_map(|limit| Op::Judge { limit }),
    ]
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(512))]

    /// RV1 + RV2 against the real ledger: coverage is the union of the
    /// delivered ranges (clipped to the file, reversed ranges swapped, line 0
    /// clamped to 1), it only grows, never exceeds the relevant lines; 100 %
    /// only when complete; complete ⇔ every planned file fully read ∧ no
    /// unreadable in-scope file; judging an answer adds no coverage and never
    /// turns PARTIAL into complete; the unread gaps are exactly the
    /// complement; a snapshot round trip keeps it all.
    #[test]
    fn ledger_is_the_set_union_and_completeness_is_honest(
        lines in prop::collection::vec(1usize..40, 1..4),
        unreadable in any::<bool>(),
        ops in prop::collection::vec(op(), 0..40),
    ) {
        let names: Vec<String> = (0..lines.len()).map(|i| format!("f{i}.rs")).collect();
        let files: Vec<(&str, usize)> =
            names.iter().map(String::as_str).zip(lines.iter().copied()).collect();
        let bad: &[&str] = if unreadable { &["big.rs (over 4.0 MB)"] } else { &[] };
        let mut s = session_with(&files, bad);
        let relevant: usize = lines.iter().sum();
        let mut model: Vec<Vec<bool>> = lines.iter().map(|&n| vec![false; n + 1]).collect();
        let mut prev_covered = 0;
        for (step, op) in ops.iter().enumerate() {
            let complete_before = s.report().complete;
            match *op {
                Op::Record { file, a, b } => {
                    // Out of the plan: ignored, like a path outside the scope.
                    let path = names.get(file).cloned().unwrap_or_else(|| "outside.rs".into());
                    s.record(&path, (a, b));
                    if let Some(bits) = model.get_mut(file) {
                        let (lo, hi) = (a.min(b).max(1), a.max(b).max(1));
                        for l in lo..=hi.min(bits.len() - 1) {
                            bits[l] = true;
                        }
                    }
                }
                Op::Judge { limit } => {
                    let covered = s.covered_lines();
                    let limit = limit.then(|| "deadline".to_string());
                    s.gate(step, &format!("answer {step} f0.rs:1"), limit);
                    prop_assert_eq!(s.covered_lines(), covered, "judging adds no coverage");
                    if !complete_before {
                        prop_assert!(!s.report().complete, "PARTIAL stays PARTIAL");
                    }
                }
            }
            let want: usize = model.iter().map(|b| b.iter().filter(|&&x| x).count()).sum();
            let covered = s.covered_lines();
            prop_assert_eq!(covered, want, "coverage = union of delivered ranges");
            prop_assert!(covered >= prev_covered, "coverage never shrinks");
            prop_assert!(covered <= relevant);
            prev_covered = covered;

            let r = s.report();
            let all_read = model.iter().zip(&lines).all(|(b, &n)| (1..=n).all(|l| b[l]));
            prop_assert_eq!(s.complete(), all_read);
            prop_assert_eq!(r.complete, all_read && !unreadable);
            prop_assert_eq!(r.read_lines, covered);
            prop_assert!(r.percent_lines < 100 || r.complete, "{} %", r.percent_lines);
            if r.complete {
                prop_assert_eq!(r.percent_lines, 100);
                prop_assert!(!r.line.contains("PARTIAL"), "{}", r.line);
            } else {
                prop_assert!(r.line.contains("PARTIAL"), "{}", r.line);
            }
            // The shard targets are exactly what is not covered.
            for (path, total, gaps) in s.unread_gaps() {
                let i = names.iter().position(|n| *n == path).unwrap();
                prop_assert_eq!(total, lines[i]);
                let mut gap_bits = vec![false; total + 1];
                for (a, b) in gaps {
                    for bit in &mut gap_bits[a..=b] {
                        prop_assert!(!*bit, "gaps overlap");
                        *bit = true;
                    }
                }
                for l in 1..=total {
                    prop_assert_eq!(gap_bits[l], !model[i][l], "line {} of {}", l, path);
                }
            }
        }
        let mut resumed = session_with(&files, bad);
        resumed.restore(&s.snapshot());
        prop_assert_eq!(resumed.covered_lines(), s.covered_lines());
        prop_assert_eq!(resumed.report().complete, s.report().complete);
    }
}

// ------------------------------------------- RV2: unreadable-only scopes

/// A scope whose every in-scope file is unreadable has nothing to read,
/// but is not a complete review: before the fix the session was dropped
/// (empty plan), so there was no coverage report and the run could end ✅.
#[test]
fn a_scope_of_only_unreadable_files_is_partial_not_absent() {
    let s = session_with(&[], &["huge.rs (over 4.0 MB)"]);
    assert!(s.needed(), "the session is kept");
    let r = s.report();
    assert!(!r.complete);
    assert_eq!(r.percent_lines, 0, "nothing was read");
    assert!(r.line.contains("PARTIAL"), "{}", r.line);
    assert!(r.line.contains("huge.rs (over 4.0 MB)"), "{}", r.line);
    // Nothing in scope at all: no session (nothing to report).
    assert!(!session_with(&[], &[]).needed());
}

#[cfg(unix)]
#[tokio::test]
async fn an_unreadable_only_review_reports_partial_coverage() {
    use std::os::unix::fs::PermissionsExt;
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    std::fs::create_dir_all(root.join("pkg")).unwrap();
    let locked = root.join("pkg/locked.py");
    std::fs::write(&locked, "def hidden():\n    return 1\n").unwrap();
    std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o000)).unwrap();
    if std::fs::read(&locked).is_ok() {
        return; // running as root: permissions do not bite
    }
    let _cwd = crate::test_support::CwdGuard::enter(root);
    let config = crate::test_support::mock_agent_config("http://127.0.0.1:9/v1");
    let mut agent = Agent::new(config).await.unwrap();
    agent.current_task_context = "review this repository for bugs".to_string();
    agent.classify_task_policy();
    agent.begin_review_session().await;
    std::fs::set_permissions(&locked, std::fs::Permissions::from_mode(0o644)).unwrap();
    let report = agent
        .review_coverage()
        .expect("an unreadable in-scope file keeps the review session");
    assert!(!report.complete, "{report:?}");
    assert!(report.line.contains("PARTIAL"), "{}", report.line);
    let base = super::super::failure_mode::FailureMode {
        restored_files: Vec::new(),
        kind: super::super::failure_mode::FailureKind::NoChange,
        evidence: "completed naturally".to_string(),
        advice: "-".to_string(),
    };
    let verdict = with_review_coverage(base, Some(&report));
    assert!(!verdict.is_clean_success(), "{}", verdict.evidence);
}

// ------------------------------------- RV3: never silently green (fold)

/// `never_silently_green`: after the gate accepts, the verdict is green only
/// for complete coverage — for every non-failure kind.
#[test]
fn partial_coverage_withholds_green_for_every_nonfailure_kind() {
    use super::super::failure_mode::{FailureKind, FailureMode};
    let mut s = session_with(&[("a.rs", 4)], &[]);
    s.record("a.rs", (1, 2));
    let partial = s.report();
    s.record("a.rs", (3, 4));
    let complete = s.report();
    assert!(!partial.complete && complete.complete);
    for kind in [FailureKind::Success, FailureKind::NoChange] {
        let base = FailureMode {
            restored_files: Vec::new(),
            kind: kind.clone(),
            evidence: "completed naturally".to_string(),
            advice: "-".to_string(),
        };
        assert!(base.is_clean_success(), "{kind:?} is green on its own");
        let folded = with_review_coverage(base.clone(), Some(&partial));
        assert!(!folded.is_clean_success(), "{kind:?}: {}", folded.evidence);
        let folded = with_review_coverage(base, Some(&complete));
        assert!(folded.is_clean_success(), "{kind:?}: {}", folded.evidence);
    }
}
